function [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
% [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
% Returns a trained regression model and its validation RMSE. The code recreates
% the model exported from Regression Learner and can retrain the same model on new data.
%
%  Input:
%      trainingData: Matrix with the same row count and data type as the matrix imported into the app.
%
%
%  Output:
%      trainedModel: Structure containing the trained regression model and related metadata.
%       The structure includes fields describing the trained model.
%
%      trainedModel.predictFcn: Function used to predict responses for new data.
%
%      validationRMSE: Double value containing the validation RMSE.
%       In the app, this is the validation RMSE shown for the model.
%
% Use this code to train the same model on new data. To retrain the model,
% call this function from the command line with original or new trainingData.
%
% For example, to retrain the regression model on matrix T, enter:
%   [trainedModel, validationRMSE] = trainRegressionModel(T)
%
% To use the returned trainedModel to predict new data T2, use:
%   yfit = trainedModel.predictFcn(T2)
%
% T2 must be a matrix containing only predictor rows used for training. For details, enter:
%   trainedModel.HowToPredict

% Automatically generated by MATLAB on 2024-03-03 17:40:21


% Extract predictors and response
% The following code reshapes the data for model training.
%
% Convert input to table
VariableNames={};
for i = 1:size(trainingData,1)
    VariableNames{1,i}=char(strcat('row_',string(i)));
    if i == size(trainingData,1)
         VariableNames{1,i}='response';
    end
end
inputTable = array2table(trainingData', 'VariableNames',VariableNames);
predictorNames = VariableNames(1:end-1);
predictors = inputTable(:, predictorNames);
response = inputTable.response;
isCategoricalPredictor = repmat([false],1,size(trainingData,1)-1);
% Apply PCA to the predictor matrix.
% PCA is run only on numeric predictors and does not process categorical predictors.
isCategoricalPredictorBeforePCA = isCategoricalPredictor;
numericPredictors = predictors(:, ~isCategoricalPredictor);
numericPredictors = table2array(varfun(@double, numericPredictors));
% Treat inf values as missing data for PCA.
numericPredictors(isinf(numericPredictors)) = NaN;
[pcaCoefficients, pcaScores, ~, ~, explained, pcaCenters] = pca(...
    numericPredictors);
% Keep enough components to explain the required variance.
explainedVarianceToKeepAsFraction = 95/100;
numComponentsToKeep = find(cumsum(explained)/sum(explained) >= explainedVarianceToKeepAsFraction, 1);
pcaCoefficients = pcaCoefficients(:,1:numComponentsToKeep);
predictors = [array2table(pcaScores(:,1:numComponentsToKeep)), predictors(:, isCategoricalPredictor)];
isCategoricalPredictor = [false(1,numComponentsToKeep), true(1,sum(isCategoricalPredictor))];

% Train regression model
% The following code specifies model options and trains the model.
regressionGP = fitrgp(...
    predictors, ...
    response, ...
    'BasisFunction', 'constant', ...
    'KernelFunction', 'matern52', ...
    'Standardize', true);

% Create the result structure with the prediction function
predictorExtractionFcn = @(x) array2table(x', 'VariableNames', predictorNames);
pcaTransformationFcn = @(x) [ array2table((table2array(varfun(@double, x(:, ~isCategoricalPredictorBeforePCA))) - pcaCenters) * pcaCoefficients), x(:,isCategoricalPredictorBeforePCA) ];
gpPredictFcn = @(x) predict(regressionGP, x);
trainedModel.predictFcn = @(x) gpPredictFcn(pcaTransformationFcn(predictorExtractionFcn(x)));

% Add fields to the result structure
trainedModel.PCACenters = pcaCenters;
trainedModel.PCACoefficients = pcaCoefficients;
trainedModel.RegressionGP = regressionGP;
trainedModel.About = 'This structure stores a trained model exported from Regression Learner R2023a.';
trainedModel.HowToPredict = sprintf('To predict with a new predictor matrix X, use: \n yfit = c.predictFcn(X) \nReplace ''c'' with the variable name of this structure, for example ''trainedModel''.\n \nX must contain exactly 678 rows because this model was trained with 678 predictors.\nX must contain only predictor rows in the same order and format as the training data. Do not include the response row or rows that were not imported into the app.\n \nFor details, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appregression_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% The following code reshapes the data for model training.
%
% Convert input to table
inputTable = array2table(trainingData', 'VariableNames',VariableNames);
predictorNames = VariableNames(1:end-1);predictors = inputTable(:, predictorNames);
response = inputTable.response;
isCategoricalPredictor = repmat([false],1,size(trainingData,1)-1);

% Perform cross-validation
KFolds = 5;
cvp = cvpartition(size(response, 1), 'KFold', KFolds);
% Initialize predictions with the correct size
validationPredictions = response;
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;

    % Apply PCA to the predictor matrix.
    % PCA is run only on numeric predictors and does not process categorical predictors.
    isCategoricalPredictorBeforePCA = foldIsCategoricalPredictor;
    numericPredictors = trainingPredictors(:, ~foldIsCategoricalPredictor);
    numericPredictors = table2array(varfun(@double, numericPredictors));
    % Treat inf values as missing data for PCA.
    numericPredictors(isinf(numericPredictors)) = NaN;
    [pcaCoefficients, pcaScores, ~, ~, explained, pcaCenters] = pca(...
        numericPredictors);
    % Keep enough components to explain the required variance.
    explainedVarianceToKeepAsFraction = 95/100;
    numComponentsToKeep = find(cumsum(explained)/sum(explained) >= explainedVarianceToKeepAsFraction, 1);
    pcaCoefficients = pcaCoefficients(:,1:numComponentsToKeep);
    trainingPredictors = [array2table(pcaScores(:,1:numComponentsToKeep)), trainingPredictors(:, foldIsCategoricalPredictor)];
    foldIsCategoricalPredictor = [false(1,numComponentsToKeep), true(1,sum(foldIsCategoricalPredictor))];

    % Train regression model
    % The following code specifies model options and trains the model.
    regressionGP = fitrgp(...
        trainingPredictors, ...
        trainingResponse, ...
        'BasisFunction', 'constant', ...
        'KernelFunction', 'matern52', ...
        'Standardize', true);

    % Create the result structure with the prediction function
    pcaTransformationFcn = @(x) [ array2table((table2array(varfun(@double, x(:, ~isCategoricalPredictorBeforePCA))) - pcaCenters) * pcaCoefficients), x(:,isCategoricalPredictorBeforePCA) ];
    gpPredictFcn = @(x) predict(regressionGP, x);
    validationPredictFcn = @(x) gpPredictFcn(pcaTransformationFcn(x));

    % Add fields to the result structure

    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    foldPredictions = validationPredictFcn(validationPredictors);

    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
end

% Compute validation RMSE
isNotMissing = ~isnan(validationPredictions) & ~isnan(response);
validationRMSE = sqrt(nansum(( validationPredictions - response ).^2) / numel(response(isNotMissing) ));
